### ISSUE TITLE
放置图片超过6P就出现问题了，没有效果显示

### ISSUE THREAD

**Issue by fhefh2015** [powy1993/fullpage#41]
* create: 2014.4.2这个版本 有同样问题
 * update: 2016.6.22 这个版本 问题依旧没有解决

背景是纯色 没问题
背景是图片且超过6P 就有问题了
测试的时候我放置了8P且背景都是图(每张图片大小60kb左右) 就出bug了

**Comment by powy1993** [comment]
你好，有测试链接吗

**Comment by fhefh2015** [comment]
@powy1993 
http://t.cn/RVezzmA

**Comment by powy1993** [comment]
不允许给 page 增加 position: relative 可以在 contain 里面使用相对布局

``` css
.page4 {
            background: url(http://mytest.dachuw.com/test/2016/11/test/images/4.jpg) no-repeat center top;
            position: relative;
        }

        .page5 {
            background: url(http://mytest.dachuw.com/test/2016/11/test/images/5.jpg) no-repeat center top;
            position: relative;
        }

        .page6 {
            background: url(http://mytest.dachuw.com/test/2016/11/test/images/6.jpg) no-repeat center top;
            position: relative;
        }

        .page7 {
            background: url(http://mytest.dachuw.com/test/2016/11/test/images/7.jpg) no-repeat center top;
            position: relative;
        }
```

这里的 position: relative 不能加。
